### ISSUE TITLE
Receive notification when app is closed but method OnNotificationReceived not working

### ISSUE THREAD

**Issue by jaspervanmegroot** [CrossGeeks/FirebasePushNotificationPlugin#41] opened 2017-10-19 11:14 UTC
I am using this for my Xamarin.Forms application but its not handeling the   CrossFirebasePushNotification.Current.OnNotificationReceived method in the Android project. I can receive a notification if the application is killed but its not handeling the method. What do I wrong?

```
[Application]
    public class MainApplication : Application
    {

        int badgeCount = 0;

        public MainApplication(IntPtr handle, JniHandleOwnership transer) : base(handle, transer)
        {
        }

        public override void OnCreate()
        {
            base.OnCreate();
            try
            {
                FirebasePushNotificationManager.Initialize(this, new NotificationUserCategory[]
                {
                        new NotificationUserCategory("message",new List<NotificationUserAction> {
                        new NotificationUserAction("Reply","Reply",NotificationActionType.Foreground),
                        new NotificationUserAction("Forward","Forward",NotificationActionType.Foreground)
                    }),
                        new NotificationUserCategory("request",new List<NotificationUserAction> {
                        new NotificationUserAction("Accept","Accept",NotificationActionType.Default,"check"),
                        new NotificationUserAction("Reject","Reject",NotificationActionType.Default,"cancel")
                    })
                }, false);

                CrossFirebasePushNotification.Current.OnTokenRefresh += (s, p) =>
                {
                    App.token = p.Token;
                    Console.WriteLine(p.Token);
                };

                CrossFirebasePushNotification.Current.Subscribe("news");

                App.token = CrossFirebasePushNotification.Current.Token;

                ME.Leolin.Shortcutbadger.ShortcutBadger.ApplyCount(this, 0);

                //Handle notification when app is closed here
                CrossFirebasePushNotification.Current.OnNotificationReceived += (s, p) =>
                {
                    badgeCount++;
                    ME.Leolin.Shortcutbadger.ShortcutBadger.ApplyCount(this, badgeCount);
                    var message = p.Data;
                    var test = s;

                    try
                    {
                        Task.Run(() => ViewModelLocator.MainChatViewModel.InitializeChatAsync()).Wait();
                    }
                    catch (Exception) { }
                };

                CrossFirebasePushNotification.Current.OnNotificationOpened += (s, p) =>
                {
                    badgeCount = 0;
                    ME.Leolin.Shortcutbadger.ShortcutBadger.ApplyCount(this, badgeCount);
                    try
                    {
                        Task.Run(() => ViewModelLocator.MainChatViewModel.InitializeChatAsync()).Wait();
                    }
                    catch (Exception) { }
                };
            }
            catch (Exception)
            {

            }
        }
    }
```

**Comment by rdelrosario** [comment] 2017-10-19 18:12
You cannot have forms related code executed when application is closed because Xamarin Forms is not initialized, that ViewModel you are using there might not be yet created. So method is getting called but since you are using stuff that might not be available when application is closed then it crashes since is null. You can use the Device Monitor to see the crash log and what's going on when app is closed but the issue is not related to the plugin, is more about handling the notification when application closed.

**Comment by rdelrosario** [comment] 2017-10-22 14:15
Let me know if have any additional questions about this. Will close this for now.

**Closed by rdelrosario** 2017-10-22 14:15 UTC
