### ISSUE TITLE
FirebasePushNotificationmanager not recognized in android's MainActivity.cs

### ISSUE THREAD

**Issue by shashikant80yadav** [CrossGeeks/FirebasePushNotificationPlugin#103] opened 2018-02-08 12:02 UTC
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin:2.2.3 
Device Tested On: Visual studio on MAC
Simulator Tested On:
Version of VS:2017
Version of Xamarin:
Versions of other things you are using:

### Steps to reproduce the Behavior
Install the package ie Plugin.FirebasePushNotification
import it in Android's MainActivity.cs i.e using Plugin.FirebasePushNotification
Under  OnCreate(Bundle bundle) method write FirebasePushNotificationManager.ProcessIntent(Intent);
Then the above class is not recognized 
I tried even compiling by setting the Target android version to 8.0 and tried several target versions but it was not recognized
I am not able to implement push notifications on android with this Plugin :-(
Though this Plugin is working great in IOS without any issues

**Comment by rdelrosario** [comment] 2018-02-08 17:48
This seems to be a duplicate of issue #100 Did you check it?

**Comment by shashikant80yadav** [comment] 2018-02-09 04:51
yes i checked it....i am setting the target android version to Oreo 8.0 but the problem still persists

**Comment by sayed-seliman** [comment] 2018-02-13 13:39
I have the same problem, did you find a solution?

**Comment by sayed-seliman** [comment] 2018-02-13 14:53
I also tryed to upgrade to 2.2.6 which has been just release but I cannot neither install it on the Android project.

**Comment by rdelrosario** [comment] 2018-02-13 18:51
Try installing:

https://www.nuget.org/packages/Plugin.FirebasePushNotification/2.2.7

**Comment by wrt** [comment] 2018-02-14 08:23
This is what you get when you inspect the package under the <Android project>->References->From Packages->Plugin.FirebasePushNotification:
![screen shot 2018-02-14 at 3 19 08 am](https://user-images.githubusercontent.com/802609/36193970-e927bdec-1135-11e8-966c-fb4f44f47a63.png)

And this is what shows up under the iOS version of the same:
![screen shot 2018-02-14 at 3 18 37 am](https://user-images.githubusercontent.com/802609/36193984-f4c5f7cc-1135-11e8-8943-ac6614cba5a8.png)

The Android one seems to have missed a bunch of components during the build, one of which is the FirebasePushNotificationManager.

**Comment by wrt** [comment] 2018-02-14 21:42
<img width="366" alt="droid-support-pkg-version" src="https://user-images.githubusercontent.com/802609/36229676-0db45e5c-11a6-11e8-857e-956346287730.png">

**Comment by rdelrosario** [comment] 2018-02-14 22:33
Ok the plugin requires 26.0.2. So that's the problem:

![image](https://user-images.githubusercontent.com/2547751/36231725-88a07ac4-11b5-11e8-8abf-64c4d87d3ef4.png)

**Comment by wrt** [comment] 2018-02-15 00:03
Painful as it was, got all the right versions of nuget/pkgs finally in, and it works well. Thank you.

**Closed** 2018-02-15 03:03 UTC

**Comment by zukolinux** [comment] 2018-02-28 18:05
Hello good afternoon, I am new with this from firebase in asp (c #), I do not understand why my notifications do not reach my mobile application, which I have placed under C #, because through the Firebase interface it works perfectly the messages I send . Then I share the code I am using and at the same time the result that I have from the firebase.

public static void SendPushNotification()

{

string response;
try
{
    string applicationID = "AAAAVXXXXXX";
    string deviceId = "BIzaSyC7RBUVCWlaOqKeup_4w1wHO";
    WebRequest tRequest = WebRequest.Create("https://fcm.googleapis.com/fcm/send");
    tRequest.Method = "POST";
    tRequest.ContentType = "application/json";
    var data = new
    {
        to = applicationID,
        notification = new
        {
            body = "Greetings",
            title = "Augsburg",
            sound = "Enabled"
            //icon = "myicon"
        },
        priority = "high"
    };

    var serializer = new JavaScriptSerializer();
    var json = serializer.Serialize(data);
    Byte[] byteArray = Encoding.UTF8.GetBytes(json);
    tRequest.Headers.Add(string.Format("Authorization: key={0}", applicationID));
    tRequest.Headers.Add(string.Format("Sender: id={0}", senderId));
    tRequest.ContentLength = byteArray.Length;
    using (Stream dataStream = tRequest.GetRequestStream())
    {
        dataStream.Write(byteArray, 0, byteArray.Length);
        using (WebResponse tResponse = tRequest.GetResponse())
        {
            using (Stream dataStreamResponse = tResponse.GetResponseStream())
            {
                using (StreamReader tReader = new StreamReader(dataStreamResponse))
                {
                    String sResponseFromServer = tReader.ReadToEnd();
                    response = sResponseFromServer;
                }
            }
        }
    }
}
catch (Exception ex)
{
    response = ex.Message;
}
}

My Firebase result is the following:
{"multicast_id":58315018627149736,"success":1,"failure":0,"canonical_ids":0,"results":[{"message_id":"0:1519772518866174%000000000000"}]}

reference link:
https://www.codeproject.com/Tips/1221681/Working-Push-Notifications-to-Android-w?msg=5469627#xx5469627xx
